# Generated by Django 5.1.7 on 2025-03-08 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_type', models.CharField(choices=[('NAT', 'persona natural'), ('JUR', 'persona jurídica')], default='NAT', max_length=3, verbose_name='tipo')),
                ('identification', models.CharField(max_length=20, unique=True, verbose_name='identificación')),
                ('name', models.CharField(max_length=200, verbose_name='nombre')),
                ('last_names', models.CharField(blank=True, max_length=200, null=True, verbose_name='apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='dirección')),
                ('mode', models.CharField(choices=[('VIR', 'virtual'), ('PRE', 'presencial')], default='VIR', max_length=3, verbose_name='modalidad')),
                ('rut', models.FileField(upload_to='documentos/', verbose_name='RUT')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('status', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='SalesAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='AdviserCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellido')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='correo electrónico')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='ciudad')),
                ('address', models.TextField(verbose_name='dirección')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='cliente')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='sales_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.salesadvisor', verbose_name='asesor comercial'),
        ),
    ]
