# Generated by Django 5.1.7 on 2025-03-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_address_customer_principal_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='last_names',
        ),
        migrations.AddField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='advisercustomer',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='advisercustomer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='advisercustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='identification',
            field=models.CharField(max_length=20, unique=True, verbose_name='identificación'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mode',
            field=models.CharField(choices=[('VIR', 'Virtual'), ('PRE', 'Presencial')], default='VIR', max_length=3, verbose_name='modalidad'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='principal_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=300, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=100, verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='salesadvisor',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='salesadvisor',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='salesadvisor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='teléfono'),
        ),
    ]
