# Generated by Django 5.1.7 on 2025-03-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_customer_last_names_customer_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón social'),
        ),
        migrations.AddField(
            model_name='customer',
            name='trade_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre comercial'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mode',
            field=models.CharField(choices=[('VIR', 'Solo Virtual'), ('PRE', 'Presencial y Virtual')], default='VIR', max_length=3, verbose_name='modalidad'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='principal_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rut',
            field=models.FileField(upload_to='documents/', verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sales_advisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customers.salesadvisor', verbose_name='Asesor Comercial HyD'),
        ),
    ]
